# Generated by Django 4.0.5 on 2022-06-19 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='adresse',
            new_name='addresse',
        ),
    ]
